app/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_security import UserMixin, RoleMixin

db = SQLAlchemy()

roles_users = db.Table('roles_users',
                       db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
                       db.Column('role_id', db.Integer(), db.ForeignKey('role.id')))


class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True)
    password = db.Column(db.String(255))
    last_login_at = db.Column(db.DateTime())
    current_login_at = db.Column(db.DateTime())
    last_login_ip = db.Column(db.String(100))
    current_login_ip = db.Column(db.String(100))
    login_count = db.Column(db.Integer)
    active = db.Column(db.Boolean())
    confirmed_at = db.Column(db.DateTime())
    unsuccessful_login_count = db.Column(db.Integer)
    blocked_until = db.Column(db.DateTime())
    roles = db.relationship('Role', secondary=roles_users,
                            backref=db.backref('users', lazy='dynamic'))

    def __str__(self):
        return f'User id={self.id}, email={self.email}'

app/forms.py
from datetime import datetime
from flask_security.forms import LoginForm

from app.models import User
from app.utils import soft_block


class CustomLoginForm(LoginForm):
    def validate(self):

        # Put code here if you want to do stuff before login attempt
        response = super(CustomLoginForm, self).validate()
        # Put code here if you want to do stuff after login attempt
        user = User.query.filter_by(email=self.email.data).first()
        if user.unsuccessful_login_count is None:
            user.unsuccessful_login_count = 0
        if user.blocked_until is None:
            user.blocked_until = datetime.utcnow()
        locktime = (datetime.utcnow() - user.blocked_until).total_seconds()
        soft_block(user, locktime)

        return response

app/__init__.py
import logging

from flask import Flask
from flask_mail import Mail
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap
from werkzeug.middleware.proxy_fix import ProxyFix
from flask_security import Security, SQLAlchemyUserDatastore

from config import Config
from app.forms import CustomLoginForm


migrate = Migrate()
bootstrap = Bootstrap()
mail = Mail()
security = Security()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    from app.models import db, User, Role
    from app.routes import main_page

    db.init_app(app)
    migrate.init_app(app, db)
    bootstrap.init_app(app)
    mail.init_app(app)
    app.wsgi_app = ProxyFix(app.wsgi_app)
    user_datastore = SQLAlchemyUserDatastore(db, User, Role)
    security.init_app(app, user_datastore, login_form=CustomLoginForm)

    app.register_blueprint(main_page)

    if app.config['LOG_TO_STDOUT']:
        stream_handler = logging.StreamHandler()
        stream_handler.setLevel(logging.INFO)
        app.logger.addHandler(stream_handler)

    return app

app/routes.py
from flask_security import login_required
from flask import Blueprint, render_template, flash, request, current_app as app

from app.utils import secure_upload

from googleapiclient.http import MediaFileUpload
from google.oauth2 import service_account
from googleapiclient.discovery import build

main_page = Blueprint('main_page', __name__, template_folder='templates')

@main_page.route('/', methods=['GET', 'POST'])
@main_page.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    if request.method == 'POST':
        credentials = service_account.Credentials.from_service_account_file(
            app.config['SERVICE_ACCOUNT_FILE'], scopes=app.config['SCOPES'])
        service = build('drive', 'v3', credentials=credentials)
        file = request.files['file']
        if secure_upload(file):
            file_metadata = {'name': file.filename,
                             'parents': [app.config['FOLDER_ID']]}
            file_path = app.config['FILE_PATH'].format(file.filename)
            media = MediaFileUpload(file_path, resumable=True)
            upload_file = service.files().create(body=file_metadata,
                                                 media_body=media,
                                                 fields='id').execute()
            flash('The file was uploaded!')
    return render_template('index.html')

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
{% if title %}{{ title }} - Google Drive Loader{% else %}Welcome to Google Drive Loader{% endif %}
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main_page.index') }}">Google Drive Loader</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_anonymous %}
                <li><a href="{{ url_for('security.login') }}">Login</a></li>
                {% else %}
                <li><a href="{{ url_for('security.logout') }}">Logout</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

{% block content %}
<div class="container">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-info" role="alert">{{ message }}</div>
    {% endfor %}
    {% endif %}
    {% endwith %}

    {# application content needs to be provided in the app_content block #}
    {% block app_content %}{% endblock %}
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

    <h1>Upload new File</h1>
    <p> Choose only 'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif' format</p>
    <form action="" method=post enctype=multipart/form-data>
      <p><input type=file name=file>
         <input type=submit value=Upload>
    </form>

{% endblock %}

app/templates/security/_macros.html
{% macro render_field_with_errors(field) %}

<div class="form-group">
    {{ field.label }} {{ field(class_='form-control', **kwargs)|safe }}
    {% if field.errors %}
    <ul>
        {% for error in field.errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>
{% endmacro %}

{% macro render_field(field) %}
<p>{{ field(class_='form-control', **kwargs)|safe }}</p>
{% endmacro %}

{% macro render_checkbox_field(field) -%}
<div class="form-group">
    <div class="checkbox">
        <label>
            {{ field(type='checkbox', **kwargs) }} {{ field.label }}
        </label>
    </div>
</div>
{%- endmacro %}

app/templates/security/login_user.html
{% extends "base.html" %}
{% from "security/_macros.html" import render_field, render_field_with_errors, render_checkbox_field %}

{% block body %}
{{ super() }}
<br><br><br><br><br>
<section class="content">
    <div class="col-sm-8 col-sm-offset-2">
        <div class="well">
                <h1>Login</h1>
            <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
                {{ login_user_form.hidden_tag() }}
                {{ render_field_with_errors(login_user_form.email) }}
                {{ render_field_with_errors(login_user_form.password) }}
                {{ render_checkbox_field(login_user_form.remember) }}
                {{ render_field(login_user_form.next) }}
                {{ render_field(login_user_form.submit, class="btn btn-primary") }}
            </form>
            <p>Not yet signed up? Please <a href="{{ url_for('security.register') }}">register for an account</a>.</p>
        </div>
    </div>
</section>
<br><br><br><br><br><br><br><br><br><br><br>
<br><br><br><br><br><br><br><br><br>
{% endblock body %}

app/templates/security/register_user.html
{% extends "base.html" %}
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
{% block body %}
{{ super() }}
<br><br><br><br>

<div class="row-fluid">
    <div class="col-sm-8 col-sm-offset-2">
    <br>
        <div class="well">
        <h1>Register</h1>
            <form action="{{ url_for_security('register') }}" method="POST" name="register_user_form">
                {{ register_user_form.hidden_tag() }}
                {{ render_field_with_errors(register_user_form.email) }}
                {{ render_field_with_errors(register_user_form.password) }}
                {% if register_user_form.password_confirm %}
                {{ render_field_with_errors(register_user_form.password_confirm) }}
                {% endif %}
                {{ render_field(register_user_form.submit, class="btn btn-primary") }}
            </form>
            <p>Already signed up? Please <a href="{{ url_for('security.login') }}">log in</a>.</p>
        </div>
    </div>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock body %}